### ISSUE TITLE
固定列数会超出显示？

### ISSUE THREAD

**Issue by StringKe** [Tsuk1ko/vue-flex-waterfall#1]
```<vue-flex-waterfall :col="column" :col-spacing="spacing" :break-by-container="true">
      <div
        v-for="(item, index) in items"
        :key="item.id"
        class="mb-1 item"
        :style="{ width: `calc(100% / ${column} - ${(spacing * (column - 1)) / column}px )`, marginBottom: `${spacing}px` }"
      >
        <div
          class="w-full h-full flex justify-center items-center p-1 bg-white rounded hover:bg-gray-400 transition duration-150 ease-in-out"
        >
          <slot :index="index" v-bind:item="item"></slot>
        </div>
      </div>
    </vue-flex-waterfall>
```
column固定为2，页面显示会出现多列
![image](https://user-images.githubusercontent.com/31089228/82541621-56f2df80-9b83-11ea-96fd-db43d3b6a194.png)
![image](https://user-images.githubusercontent.com/31089228/82541638-5eb28400-9b83-11ea-9396-8b21276f1c6b.png)

**Comment by Tsuk1ko** [comment]
可能高度计算还有点问题……

试一下临时把这个 height 调高几 px 是不是会恢复正常

![image](https://user-images.githubusercontent.com/24877906/82542339-658dc680-9b84-11ea-82b6-3a3e3d78cab3.png)

**Comment by StringKe** [comment]
由于图片需要加载，获取的高度不正确导致的，默认的height能否传递？

**Comment by Tsuk1ko** [comment]
现在还不能，是自动计算，我在下一版本加上手动指定的选项

可能是图片加载不触发 MutationObserver ……

目前可以先试试监听图片`onload`，通过 ref 调用组件的`updateOrder`方法，后续我看看有没有办法改进

**Comment by StringKe** [comment]
~~添加了一个额外的参数强制指定 height 为 auto~~

我这里是已知高度的不太合适

**Comment by Tsuk1ko** [comment]
现在可以手动指定高度了

~新版本也会对 img 的 load 事件进行捕获，并更新 order，不过我试了下并不太理想，因为只有图片加载完成后才会触发这个事件，而图片开始加载的时候它的长宽就已经更新了，图片加载的过程中仍然会保持挤出去的状态~

我推荐这些做法：

1. 如你所说你的高度已知的情况下可以手动指定容器高度
2. 使用图片懒加载组件，总之等图片完全加载完毕再放上去
3. 提前知道图片的长宽比，提前把元素的宽高固定好
