### ISSUE TITLE
遇到图片自动撑开高度，没有换行

### ISSUE THREAD

**Issue by MrRabbit1993** [Tsuk1ko/vue-flex-waterfall#13]
当遇到内部item的高度是由图片自动撑开时，所有item在全一行，没有换行

**Comment by Tsuk1ko** [comment]
https://github.com/Tsuk1ko/vue-flex-waterfall/issues/8#issuecomment-1051568702

https://github.com/Tsuk1ko/vue-flex-waterfall/blob/master/README-ZH.md#%E6%8F%90%E7%A4%BA
