### ISSUE TITLE
Can't make it work with Nuxt

### ISSUE THREAD

**Issue by ghost** [Tsuk1ko/vue-flex-waterfall#3]
I just tried your plugin which seems very promising, but I can't make it work with Nuxt. Any solution for that? Thanks

**Comment by Tsuk1ko** [comment]
Do you have an example repository?

**Comment by CavalcanteLeo** [comment]
got this error:

MutationObserver is not defined

**Comment by Tsuk1ko** [comment]
> got this error:
> 
> MutationObserver is not defined

Try to install a MutationObserver polyfill?

Such as [mutationobserver-shim](https://www.npmjs.com/package/mutationobserver-shim)

**Comment by rlam3** [comment]
@ezimmert Were you able to get a workaround? I'm having a similar issue and unable to get this package to work with Nuxt.js

@Tsuk1ko I installed the package you described but was unsuccessful and got the following error:

```
 ERROR  [Vue warn]: Error in data(): "ReferenceError: MutationObserver is not defined"
```

**Comment by Tsuk1ko** [comment]
@rlam3 Did you import mutationobserver-shim before import vue-flex-waterfall?

**Comment by rlam3** [comment]
@Tsuk1ko import you mean `npm install` correct?

my package.json already installed it.
```
package.json

...
    "mutationobserver-shim": "^0.3.7",
...
    "vue-flex-waterfall": "^1.0.7",
...
```


Or do you mean I need to import mutationobserver-shim into my component before vue-flex-waterfall?

**Comment by Tsuk1ko** [comment]
@rlam3 Yes, like this:

```js
import 'mutationobserver-shim';
import VueFlexWaterfall from 'vue-flex-waterfall';

export default {
  components: { VueFlexWaterfall }
}
```

**Comment by rlam3** [comment]
@Tsuk1ko 

```
<template>
  <div>
    <h1>GalleryWaterfall</h1>
    <vue-flex-waterfall
      col="2"
      col-spacing="15"
      :break-at="{ 900: 3, 600: 2, 300: 1 }"
    >
      <div>test</div>
    </vue-flex-waterfall>
  </div>
</template>

<script>
import 'mutationobserver-shim'
import VueFlexWaterfall from 'vue-flex-waterfall'
export default {
  props: {
    listOfItems: Object
  },
  components: {
    VueFlexWaterfall
  },
  name: 'WaterfallGallery',
  data() {
    return {
      items: [
        {
          i: 1
        }
      ]
    }
  }
}
</script>

<style lang="" scoped>
</style>

```

Is there something I need to update in my nuxt.config.js to make this transpile? Or can you provide me with a demo that works with nuxt? Thank you!

**Comment by rlam3** [comment]
I have switched to this repo instead. https://github.com/paulcollett/vue-masonry-css for now. 

This plugin unfortunately did not work with my nuxt.js app.

**Comment by dragon-fish** [comment]
I may have found a solution. Move DOM operation into onMounted hook.

**Comment by Tsuk1ko** [comment]
v2.2.1 has fully supported nuxt.
