### ISSUE TITLE
您好！请问支持vue3吗 为什么我使用的时候全部图片都挤在一列呢的呢

### ISSUE THREAD

**Issue by chitanderu** [Tsuk1ko/vue-flex-waterfall#8]

**Comment by Tsuk1ko** [comment]
虽然是 vue2 开发的，但因为模板语法是兼容的，所以理论上通过 npm 安装再引用是支持 vue3 的

如果通过 cdn 引用 js 就只支持 vue2

因为图片未加载的时候长宽是 0，所以一开始计算的时候都会堆在第一列，有两种解决办法：

1. 如果事先知道图片长宽比，外层使用 div 提前占位
2. 图片加载完后手动调用 updateOrder

**Comment by chitanderu** [comment]
谢谢您 可以详细请教一下第二种方法吗  具体要怎么调用呢

**Comment by Tsuk1ko** [comment]
通过 ref 调用组件的 updateOrder 函数

**Comment by Tsuk1ko** [comment]
现已正式支持 Vue 3
