### ISSUE TITLE
Is this supposed to work on VUE 3?

### ISSUE THREAD

**Issue by MarisKay** [Tsuk1ko/vue-flex-waterfall#9]
Did everything as mentioned in your example. But i get an error:

runtime-core.esm-bundler.js?9e79:38 [Vue warn]: Unhandled error during execution of mounted hook 
  at <VueFlexWaterfall col=4 col-spacing=15 break-at= {300: 1, 600: 2, 900: 3}  ... > 
  at <Discover style= {width: '1200px'} onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <RouterView key=0 style= {width: '1200px'} > 
  at <MainLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <RouterView> 
  at <App>

**Comment by MarisKay** [comment]
Uncaught TypeError: (this.$slots.default || []).map is not a function
    at Proxy.items (Waterfall.vue?0779:87:1)
    at Proxy.updateOrder (Waterfall.vue?0779:98:1)
    at onLoadCapture._cache.<computed>._cache.<computed> (Waterfall.vue?0779:6:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js?9e79:155:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?9e79:164:1)
    at HTMLDivElement.invoker (runtime-dom.esm-bundler.js?8886:369:1)
runtime-core.esm-bundler.js?9e79:38 [Vue warn]: Unhandled error during execution of native event handler 
  at <VueFlexWaterfall key=0 col=4 col-spacing=15  ... > 
  at <Discover style= Object onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy > > 
  at <RouterView key=0 style= Object > 
  at <MainLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy > > 
  at <RouterView> 
  at <App>

**Comment by Tsuk1ko** [comment]
Hi, it support Vue 3 now, please use v2.
